<?php
echo "<footer>"
. "<p>Copyright &#169; 2024 NEBULA</p>"
.   "<div>"
.       "<a href=\"https://youtu.be/ZV7AfCQub1Q\">Youtube</a>"
.       "<a href=\"https://twitter.com/nebula2024\">Twitter</a>"
.       "<a href=\"mailto:103603101@student.swin.edu.au\">Email</a>"
.       "<a href=\"https://github.com/HarryMacheda/COS10026-Project\">Github</a>"
.       "<a>👋</a>"
.   "</div>"
. "</footer>";
?>