<?php
echo "<nav>"
. "<img src=\"./images/tiny_logo.png\" alt=\"\">"
. "<div id=\"navDesktop\">"
. "<a href=\"./index.php\"><span class=\"fa-solid fa-house\" aria-hidden=\"true\"></span>Home</a>"
. "<a href=\"./jobs.php\"><span class=\"fa-solid fa-user-tie\" aria-hidden=\"true\"></span>Jobs</a>"
. "<a href=\"./apply.php\"><span class=\"fa-solid fa-file-contract\" aria-hidden=\"true\"></span>Application</a>"
. "<a href=\"./about.php\"><span class=\"fa-solid fa-people-group\" aria-hidden=\"true\"></span>About Us</a>"
. " <a href=\"./enhancements.php\"><span class=\"fa-solid fa-star\" aria-hidden=\"true\"></span>Enhancements</a>"
. "</div>"
. " <div id="navMobile">"
. "<span class="fa-solid fa-bars" aria-hidden="true" onclick=""></span>"
. "<div>
. "<a href="./index.php"><span class="fa-solid fa-house" aria-hidden="true"></span>Home</a>"
. "<a href="./jobs.php"><span class="fa-solid fa-user-tie" aria-hidden="true"></span>Jobs</a>"                   
. "<a href="./apply.php"><span class="fa-solid fa-file-contract" aria-hidden="true"></span>Application</a>"
. "<a href="./about.php"><span class="fa-solid fa-people-group" aria-hidden="true"></span>About Us</a>"
. " <a href="./enhancements.php"><span class="fa-solid fa-star" aria-hidden="true"></span>Enhancements</a>"
. "</div>"
. "</div>";
. "</nav>";
?>