<?php
echo "<img src="./images/tiny_logo.png" alt="">"
echo "<div id="navDesktop">"
echo "<a href="./index.html"><span class="fa-solid fa-house" aria-hidden="true"></span>Home</a>"
echo "<a href="./jobs.html"><span class="fa-solid fa-user-tie" aria-hidden="true"></span>Jobs</a>"                   
echo "<a href="./apply.html"><span class="fa-solid fa-file-contract" aria-hidden="true"></span>Application</a>"
echo "<a href="./about.html"><span class="fa-solid fa-people-group" aria-hidden="true"></span>About Us</a>"
echo " <a href="./enhancements.html"><span class="fa-solid fa-star" aria-hidden="true"></span>Enhancements</a>"
echo "</div>"

echo " <div id="navMobile">"
echo "<span class="fa-solid fa-bars" aria-hidden="true" onclick=""></span>"
echo "<div>
echo "<a href="./index.html"><span class="fa-solid fa-house" aria-hidden="true"></span>Home</a>"
echo "<a href="./jobs.html"><span class="fa-solid fa-user-tie" aria-hidden="true"></span>Jobs</a>"                   
echo "<a href="./apply.html"><span class="fa-solid fa-file-contract" aria-hidden="true"></span>Application</a>"
echo "<a href="./about.html"><span class="fa-solid fa-people-group" aria-hidden="true"></span>About Us</a>"
echo " <a href="./enhancements.html"><span class="fa-solid fa-star" aria-hidden="true"></span>Enhancements</a>"
echo "</div>"
echo "</div>";
?>